name: Main Terraform Workflow

on:
  push:
    branches:
      - main
      - develop
      - "feature/*"

permissions:
  id-token: write
  contents: read

jobs:
  deploy-dev:
    name: Deploy to Dev
    uses: ./.github/workflows/terraform-deploy.yml
    with:
      environment: dev
      aws_account_id: "474668415523"
    secrets:
      google_client_secret: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
      anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}

  deploy-prod:
    name: Deploy to Prod
    needs: deploy-dev
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
    uses: ./.github/workflows/terraform-deploy.yml
    with:
      environment: prod
      aws_account_id: "054037129431"
    secrets:
      google_client_secret: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
      anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
